# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='backfills/')),
            ],
        ),
        migrations.AddField(
            model_name='abstractitem',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfieldentry',
            name='per_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='understocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='suggestion',
            field=models.CharField(choices=[('D', 'Disbursement'), ('L', 'Loan'), ('B', 'Backfill')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='cart_request',
            name='suggestion',
            field=models.CharField(choices=[('D', 'Disbursement'), ('L', 'Loan'), ('B', 'Backfill')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AbstractItem'),
        ),
        migrations.AddField(
            model_name='backfillpdf',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Request'),
        ),
    ]
