# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170403_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='understocked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
