# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170403_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='backfills/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Request')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='understocked',
            field=models.BooleanField(default=False),
        ),
    ]
