# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_abstractitem_is_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractitem',
            name='is_asset',
        ),
        migrations.AddField(
            model_name='item',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
    ]
