# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_request_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='testField',
        ),
    ]
