# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170405_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='suggestion',
            field=models.CharField(choices=[('D', 'Disbursement'), ('L', 'Loan'), ('B', 'Backfill')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='cart_request',
            name='suggestion',
            field=models.CharField(choices=[('D', 'Disbursement'), ('L', 'Loan'), ('B', 'Backfill')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Disbursed'), ('D', 'Denied'), ('P', 'In Progress'), ('L', 'Loaned'), ('R', 'Returned'), ('B', 'For Backfill'), ('Z', 'Hacky Log Status')], default='O', max_length=1),
        ),
    ]
