# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170411_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AbstractItem'),
        ),
    ]
