# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170405_1443'),
        ('home', '0006_auto_20170413_1428'),
    ]

    operations = [
    ]
