# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170204_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_id',
            new_name='owner',
        ),
    ]
