# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170205_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Approved'), ('D', 'Denied')], default='O', max_length=1),
        ),
    ]
