# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170410_1944'),
        ('home', '0008_auto_20170416_1743'),
    ]

    operations = [
    ]
