# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20170416_1902'),
        ('home', '0009_merge_20170416_1806'),
    ]

    operations = [
    ]
