# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_request_admin_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='total_count',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_available',
        ),
    ]
