# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='parent_cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cart_Request'),
        ),
    ]
