# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170214_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='home.Item'),
        ),
    ]
