# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170214_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='tag',
        ),
    ]
