# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cart_request_is_active_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomLongTextField',
            fields=[
                ('customfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.CustomField')),
                ('field_value', models.TextField()),
            ],
            bases=('home.customfield',),
        ),
        migrations.AddField(
            model_name='customfield',
            name='for_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item'),
        ),
    ]
