# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170220_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIntField',
            fields=[
                ('customfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.CustomField')),
                ('field_value', models.IntegerField()),
            ],
            bases=('home.customfield',),
        ),
        migrations.CreateModel(
            name='CustomShortTextField',
            fields=[
                ('customfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.CustomField')),
                ('field_value', models.CharField(max_length=70)),
            ],
            bases=('home.customfield',),
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='for_item',
            new_name='parent_item',
        ),
    ]
