# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_merge_20170220_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('is_private', models.BooleanField()),
                ('value_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFloatField',
            fields=[
                ('customfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.CustomField')),
                ('field_value', models.FloatField()),
            ],
            bases=('home.customfield',),
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CustomFieldEntry'),
        ),
    ]
