# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_merge_20170220_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_user', to=settings.AUTH_USER_MODEL)),
                ('initiating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiating_user', to=settings.AUTH_USER_MODEL)),
                ('involved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Item')),
            ],
        ),
    ]
