# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170221_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
    ]
