# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_item_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
