# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170220_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='involved_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Item'),
        ),
    ]
