# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170221_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='affected_user',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='initiating_user',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='involved_item',
            field=models.IntegerField(db_index=True),
        ),
    ]
