# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170221_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='related_request',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
