# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_log_related_request'),
        ('home', '0020_auto_20170224_1009'),
    ]

    operations = [
    ]
