# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_merge_20170224_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshorttextfield',
            name='field_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
