# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170224_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='involved_item',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
