# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20170226_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_request',
            name='is_active_request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='reason',
        ),
        migrations.AlterField(
            model_name='cart_request',
            name='cart_status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'In Progress')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'In Progress')], default='O', max_length=1),
        ),
    ]
