# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20170227_2310'),
        ('home', '0028_auto_20170227_2306'),
    ]

    operations = [
    ]
