# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_merge_20170227_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
