# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_emailbody_emailtag_loandate_subscribedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_request',
            name='suggestion',
            field=models.CharField(choices=[('D', 'Disbursement'), ('L', 'Loan')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='cart_request',
            name='cart_status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'In Progress'), ('L', 'Loaned')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='admin_comment',
            field=models.TextField(default='No Comment'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'In Progress'), ('L', 'Loaned'), ('R', 'Returned')], default='O', max_length=1),
        ),
    ]
