# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20170323_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('O', 'Outstanding'), ('A', 'Approved'), ('D', 'Denied'), ('P', 'In Progress'), ('L', 'Loaned'), ('R', 'Returned'), ('Z', 'Hacky Log Status')], default='O', max_length=1),
        ),
    ]
